id: fe8cf7b7-d310-456d-8a8b-4dcfd5d52f38
version: 3
name: Extractfile_punniya_text
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: c33f0130-16ad-4d6f-86ac-53c4c827de3a
    type: start
    task:
      id: c33f0130-16ad-4d6f-86ac-53c4c827de3a
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 705,
          "y": 10
        }
      }
    note: false
  "1":
    id: "1"
    taskid: af5222f5-ebeb-45f4-85a4-4c800fa9eb1b
    type: condition
    task:
      id: af5222f5-ebeb-45f4-85a4-4c800fa9eb1b
      version: -1
      name: Do we have any attachment?
      script: Exists
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "no":
      - "13"
      "yes":
      - "2"
    scriptarguments:
      value:
        simple: ${File(val.Extension=='txt')}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 705,
          "y": 195
        }
      }
    note: false
  "2":
    id: "2"
    taskid: 968e8470-95d7-4938-8a93-f77f1f4065cb
    type: regular
    task:
      id: 968e8470-95d7-4938-8a93-f77f1f4065cb
      version: -1
      name: Read attachment
      script: ParseWordDoc
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      entryID:
        simple: ${File(val.Extension=='txt').EntryID}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 490,
          "y": 370
        }
      }
    note: false
  "3":
    id: "3"
    taskid: 801c1c00-575b-49dc-816f-95b113f8b064
    type: regular
    task:
      id: 801c1c00-575b-49dc-816f-95b113f8b064
      version: -1
      name: Read file from the copied text
      script: ReadFile
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "4"
      - "5"
      - "6"
    scriptarguments:
      entryID:
        simple: ${File(val.Extension=='txt').EntryID}
      maxFileSize: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 490,
          "y": 545
        }
      }
    note: false
  "4":
    id: "4"
    taskid: f9aa1020-52fd-41ef-8850-924cb4b4fd2e
    type: regular
    task:
      id: f9aa1020-52fd-41ef-8850-924cb4b4fd2e
      version: -1
      name: Extract ip
      script: ExtractIP
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "7"
    scriptarguments:
      text:
        simple: ${FileData}${incident.details}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 60,
          "y": 720
        }
      }
    note: false
  "5":
    id: "5"
    taskid: a811674a-7f37-4fd9-8d87-0ec5de01350e
    type: regular
    task:
      id: a811674a-7f37-4fd9-8d87-0ec5de01350e
      version: -1
      name: Extract Domain
      script: ExtractDomain
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "10"
    scriptarguments:
      calcReputation: {}
      extractFromEmails: {}
      markAsIndicator: {}
      text:
        simple: ${FileData}${incident.details}
      tldList: {}
      urlRegex: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 920,
          "y": 895
        }
      }
    note: false
  "6":
    id: "6"
    taskid: 5801e9f2-1509-484a-85eb-aff721069170
    type: regular
    task:
      id: 5801e9f2-1509-484a-85eb-aff721069170
      version: -1
      name: extract url
      script: ExtractURL
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "8"
    scriptarguments:
      text:
        simple: ${FileData}${incident.details}
      urlRegex: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 490,
          "y": 720
        }
      }
    note: false
  "7":
    id: "7"
    taskid: d6a69ba4-8c4e-4345-8922-74f67115afdb
    type: regular
    task:
      id: d6a69ba4-8c4e-4345-8922-74f67115afdb
      version: -1
      name: check IP reputation
      script: IPReputation
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "9"
    scriptarguments:
      ip:
        simple: ${IP.Address}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 60,
          "y": 895
        }
      }
    note: false
  "8":
    id: "8"
    taskid: a274c1c7-69c5-44a2-823d-624a5b72e139
    type: regular
    task:
      id: a274c1c7-69c5-44a2-823d-624a5b72e139
      version: -1
      name: url reputation
      script: URLReputation
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "10"
    scriptarguments:
      url:
        simple: ${URL.Data}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 490,
          "y": 895
        }
      }
    note: false
  "9":
    id: "9"
    taskid: 59d23849-d620-4191-8482-d017693031ad
    type: condition
    task:
      id: 59d23849-d620-4191-8482-d017693031ad
      version: -1
      name: check malicious
      script: IsMaliciousIndicatorFound
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "no":
      - "12"
      "yes":
      - "11"
    scriptarguments:
      extend-context:
        simple: data
      includeSuspicious:
        simple: "yes"
      maliciousQueryOverride: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 60,
          "y": 1070
        }
      }
    note: false
  "10":
    id: "10"
    taskid: fd39e3c1-7f8e-41d1-8208-baac2c03f1ed
    type: condition
    task:
      id: fd39e3c1-7f8e-41d1-8208-baac2c03f1ed
      version: -1
      name: check malicious
      script: IsMaliciousIndicatorFound
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "no":
      - "12"
      "yes":
      - "11"
    scriptarguments:
      extend-context:
        simple: URL Data
      includeSuspicious:
        simple: "yes"
      maliciousQueryOverride: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 490,
          "y": 1070
        }
      }
    note: false
  "11":
    id: "11"
    taskid: b264fcf3-6cce-4b4f-8911-68137eab04e9
    type: regular
    task:
      id: b264fcf3-6cce-4b4f-8911-68137eab04e9
      version: -1
      name: assign it to user
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "14"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1245
        }
      }
    note: false
  "12":
    id: "12"
    taskid: 5001fc92-742b-451e-836b-f67546a8ead0
    type: regular
    task:
      id: 5001fc92-742b-451e-836b-f67546a8ead0
      version: -1
      name: close investigation
      script: CloseInvestigation
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "14"
    scriptarguments:
      notes:
        simple: Task has been successfully completed
      reason: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 510,
          "y": 1245
        }
      }
    note: false
  "13":
    id: "13"
    taskid: c4c87cc1-dafd-4dd1-86c2-50974c2358fb
    type: regular
    task:
      id: c4c87cc1-dafd-4dd1-86c2-50974c2358fb
      version: -1
      name: close investigation
      script: CloseInvestigation
      type: regular
      iscommand: false
      brand: ""
    scriptarguments:
      notes:
        simple: There is no attachements
      reason: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 920,
          "y": 370
        }
      }
    note: false
  "14":
    id: "14"
    taskid: 19124e25-552f-4443-80c6-9b693d1eff20
    type: title
    task:
      id: 19124e25-552f-4443-80c6-9b693d1eff20
      version: -1
      name: close investigation
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 275,
          "y": 1420
        }
      }
    note: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1475,
        "width": 1250,
        "x": 50,
        "y": 10
      }
    }
  }
inputs: []
outputs: []
