id: 9a6e2513-c7d5-4a37-8b0c-5401f4bf340e
version: 9
name: Email - Testing _copy
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 395847b5-90ad-48ba-8ccd-bffe3c5810e2
    type: start
    task:
      id: 395847b5-90ad-48ba-8ccd-bffe3c5810e2
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "4"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
    note: false
  "4":
    id: "4"
    taskid: 8ecdedb8-a259-426d-8181-4a6d1fcd8060
    type: regular
    task:
      id: 8ecdedb8-a259-426d-8181-4a6d1fcd8060
      version: -1
      name: SendEmail
      description: |-
        Send an email with the specified parameters.
        Attachments are provided as a comma-separated list of entry IDs.
        Example usage: !SendEmail subject="File from war room" body="Please see the attached file. --DBot" to=jane@acme.com cc=john@acme.com attachIDs=89@3,46@3
      script: exchange_mail_test|||send-mail
      type: regular
      iscommand: true
      brand: exchange_mail_test
    scriptarguments:
      attachIDs:
        simple: 296@6765aae3-461c-41e3-83e9-9153c9aba79f
      attachNames: {}
      bcc: {}
      body:
        simple: testing
      cc: {}
      fileName: {}
      htmlBody: {}
      replyTo: {}
      subject:
        simple: 'Extracted IP '
      to:
        simple: s.kumar10@wipro.com
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 282
        }
      }
    note: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 327,
        "width": 380,
        "x": 450,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
