id: 4173c286-e723-484c-8121-db5b4a413d3c
version: 3
name: MOG-Malware Playbook
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 64f94958-e7f7-4206-8e7b-51fc5556a5f2
    type: start
    task:
      id: 64f94958-e7f7-4206-8e7b-51fc5556a5f2
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "19"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 592.5,
          "y": 50
        }
      }
    note: false
  "6":
    id: "6"
    taskid: 1a75092c-07ae-4b99-844f-8867639f2581
    type: regular
    task:
      id: 1a75092c-07ae-4b99-844f-8867639f2581
      version: -1
      name: Close the Investigation
      script: CloseInvestigation
      type: regular
      iscommand: false
      brand: ""
    scriptarguments:
      notes: {}
      reason: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
    note: false
  "7":
    id: "7"
    taskid: cbcdf9c0-0120-427c-864d-289915ebc40e
    type: regular
    task:
      id: cbcdf9c0-0120-427c-864d-289915ebc40e
      version: -1
      name: Print Agent host name
      script: Print
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "9"
    scriptarguments:
      value:
        simple: ${FireeyeHelix-Context.alertTypeDetails.detail.agenthostname}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1022.5,
          "y": 545
        }
      }
    note: false
  "9":
    id: "9"
    taskid: b149a409-f20b-49bf-8886-12ba5f04b5ab
    type: regular
    task:
      id: b149a409-f20b-49bf-8886-12ba5f04b5ab
      version: -1
      name: AD User Information
      script: ADGetUser
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "23"
    scriptarguments:
      attributes: {}
      customFieldData: {}
      customFieldType: {}
      dn: {}
      email: {}
      headers: {}
      limit: {}
      name: {}
      nestedSearch: {}
      userAccountControlOut: {}
      username: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1022.5,
          "y": 720
        }
      }
    note: false
  "11":
    id: "11"
    taskid: af96737b-94b0-478c-8551-31a1b0c0aa5b
    type: regular
    task:
      id: af96737b-94b0-478c-8551-31a1b0c0aa5b
      version: -1
      name: Malware Reputation
      script: VirusTotal|||file
      type: regular
      iscommand: true
      brand: VirusTotal
    nexttasks:
      '#none#':
      - "30"
    scriptarguments:
      file: {}
      long: {}
      retries: {}
      threshold: {}
      wait: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 592.5,
          "y": 720
        }
      }
    note: false
  "12":
    id: "12"
    taskid: 33d2dcc6-40e4-4783-81e9-0863db780989
    type: regular
    task:
      id: 33d2dcc6-40e4-4783-81e9-0863db780989
      version: -1
      name: DAT version check
      script: epo|||epo-get-current-dat
      type: regular
      iscommand: true
      brand: epo
    nexttasks:
      '#none#':
      - "22"
    scriptarguments:
      extend-context: {}
      using:
        simple: epo_instance_1
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 592.5,
          "y": 1070
        }
      }
    note: false
  "13":
    id: "13"
    taskid: 9287e993-00c1-4b25-8dc0-9319db9698e1
    type: regular
    task:
      id: 9287e993-00c1-4b25-8dc0-9319db9698e1
      version: -1
      name: DAT Update
      script: epo|||epo-update-client-dat
      type: regular
      iscommand: true
      brand: epo
    nexttasks:
      '#none#':
      - "14"
    scriptarguments:
      abortAfterMinutes: {}
      randomizationInterval: {}
      retryAttempts: {}
      retryIntervalInSeconds: {}
      stopAfterMinutes: {}
      systems: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 592.5,
          "y": 1420
        }
      }
    note: false
  "14":
    id: "14"
    taskid: 202177d2-5c50-43d0-82c4-f6f238beaa08
    type: regular
    task:
      id: 202177d2-5c50-43d0-82c4-f6f238beaa08
      version: -1
      name: Reinitiate Scan
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "25"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 592.5,
          "y": 1595
        }
      }
    note: false
  "16":
    id: "16"
    taskid: fafc61d4-6f9e-411e-82bf-1bbcf09be21d
    type: regular
    task:
      id: fafc61d4-6f9e-411e-82bf-1bbcf09be21d
      version: -1
      name: Assign to L2 for further investigation
      script: AssignAnalystToIncident
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "27"
    scriptarguments:
      assignBy:
        simple: random
      email: {}
      roles: {}
      username: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 377.5,
          "y": 2120
        }
      }
    note: false
  "19":
    id: "19"
    taskid: 05169493-2dc4-4a74-8b20-90dc27474456
    type: condition
    task:
      id: 05169493-2dc4-4a74-8b20-90dc27474456
      version: -1
      name: AV Output Action
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      Blocked:
      - "21"
      Deleted:
      - "34"
      Quarantined:
      - "6"
      UnQuarantined:
      - "20"
    separatecontext: false
    conditions:
    - label: Quarantined
      condition:
      - - operator: isEqualString
          left:
            value:
              simple: ${FireeyeHelix-Context.alertTypeDetails.detail.result}
            iscontext: true
          right:
            value:
              simple: Quarantined
          ignorecase: true
    - label: UnQuarantined
      condition:
      - - operator: isEqualString
          left:
            value:
              simple: ${FireeyeHelix-Context.alertTypeDetails.detail.result}
            iscontext: true
          right:
            value:
              simple: UnQuarantined
    - label: Deleted
      condition:
      - - operator: isEqualString
          left:
            value:
              simple: ${FireeyeHelix-Context.alertTypeDetails.detail.result}
            iscontext: true
          right:
            value:
              simple: Deleted
    - label: Blocked
      condition:
      - - operator: isEqualString
          left:
            value:
              simple: ${FireeyeHelix-Context.alertTypeDetails.detail.result}
            iscontext: true
          right:
            value:
              simple: Blocked
    view: |-
      {
        "position": {
          "x": 592.5,
          "y": 195
        }
      }
    note: false
  "20":
    id: "20"
    taskid: c46e8557-4ebb-4105-8eb7-4fc6e2c8f438
    type: title
    task:
      id: c46e8557-4ebb-4105-8eb7-4fc6e2c8f438
      version: -1
      name: 'Extract Threat Information '
      type: title
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "7"
      - "21"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 475,
          "y": 411
        }
      }
    note: false
  "21":
    id: "21"
    taskid: f69acb84-aa67-46eb-8f8a-d60453fb292a
    type: regular
    task:
      id: f69acb84-aa67-46eb-8f8a-d60453fb292a
      version: -1
      name: Malware Details
      script: Print
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "11"
    scriptarguments:
      value:
        simple: ${FireeyeHelix-Context.alertTypeDetails.summary.virus}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 592.5,
          "y": 545
        }
      }
    note: false
  "22":
    id: "22"
    taskid: 45f409ad-e2e7-4207-86f0-9596128d3f6e
    type: regular
    task:
      id: 45f409ad-e2e7-4207-86f0-9596128d3f6e
      version: -1
      name: Check latest DAT file in McAfee repository
      script: epo|||epo-get-latest-dat
      type: regular
      iscommand: true
      brand: epo
    nexttasks:
      '#none#':
      - "13"
    scriptarguments:
      using:
        simple: epo_instance_1
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 592.5,
          "y": 1245
        }
      }
    note: false
  "23":
    id: "23"
    taskid: af6c602e-eba8-4bfa-8b56-7464d18a27f8
    type: regular
    task:
      id: af6c602e-eba8-4bfa-8b56-7464d18a27f8
      version: -1
      name: Get Emails
      script: ContextGetEmails
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "24"
    scriptarguments:
      excludedEmails: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1022.5,
          "y": 895
        }
      }
    note: false
  "24":
    id: "24"
    taskid: d5ae5bb1-751c-4ac7-8173-f0bd27088028
    type: regular
    task:
      id: d5ae5bb1-751c-4ac7-8173-f0bd27088028
      version: -1
      name: Send Email to User to Change Credentials
      script: SendEmail
      type: regular
      iscommand: false
      brand: ""
    scriptarguments:
      attachIDs: {}
      bcc: {}
      body: {}
      cc: {}
      htmlBody: {}
      noteEntryID: {}
      replyTo: {}
      subject:
        simple: Machine got infected | Change Login Credentials
      to: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1022.5,
          "y": 1070
        }
      }
    note: false
  "25":
    id: "25"
    taskid: 191178ca-4391-4276-8464-2a2bca55129f
    type: condition
    task:
      id: 191178ca-4391-4276-8464-2a2bca55129f
      version: -1
      name: Check Infection
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "33"
      "yes":
      - "26"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualString
          left:
            value:
              simple: ${FireeyeHelix-Context.alertTypeDetails.detail.result}
            iscontext: true
          right:
            value:
              simple: Unquarantined
    view: |-
      {
        "position": {
          "x": 592.5,
          "y": 1770
        }
      }
    note: false
  "26":
    id: "26"
    taskid: 6082e555-fea6-480c-8222-7e971f3825db
    type: regular
    task:
      id: 6082e555-fea6-480c-8222-7e971f3825db
      version: -1
      name: Send Email to L2 Analyst
      script: mail-sender|||send-mail
      type: regular
      iscommand: true
      brand: mail-sender
    nexttasks:
      '#none#':
      - "16"
    scriptarguments:
      attachIDs: {}
      attachNames: {}
      bcc: {}
      body: {}
      cc: {}
      htmlBody: {}
      replyTo: {}
      subject: {}
      to: {}
      transientFile: {}
      transientFileContent: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 377.5,
          "y": 1945
        }
      }
    note: false
  "27":
    id: "27"
    taskid: 31b769ce-8a4c-4df7-85f6-63f4d342e02a
    type: title
    task:
      id: 31b769ce-8a4c-4df7-85f6-63f4d342e02a
      version: -1
      name: Decision to close the Investigation
      type: title
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "28"
      - "31"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 377.5,
          "y": 2295
        }
      }
    note: false
  "28":
    id: "28"
    taskid: 409d7864-72ba-4685-8da1-442d4c7a3870
    type: condition
    task:
      id: 409d7864-72ba-4685-8da1-442d4c7a3870
      version: -1
      name: Close Investigation
      script: CloseInvestigation
      type: condition
      iscommand: false
      brand: ""
    scriptarguments:
      extend-context: {}
      notes: {}
      reason: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 2440
        }
      }
    note: false
  "30":
    id: "30"
    taskid: 0ad54f59-ac18-40a4-8181-fd27bdbec3be
    type: condition
    task:
      id: 0ad54f59-ac18-40a4-8181-fd27bdbec3be
      version: -1
      name: Get other systems infected with the same Threat in last 24 hours
      script: IsMaliciousIndicatorFound
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "12"
    scriptarguments:
      includeSuspicious:
        simple: "yes"
      maliciousQueryOverride: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 592.5,
          "y": 895
        }
      }
    note: false
  "31":
    id: "31"
    taskid: fddd236d-035c-4240-8cbf-fb8c329e9977
    type: regular
    task:
      id: fddd236d-035c-4240-8cbf-fb8c329e9977
      version: -1
      name: Please provide justification for not closing the incident at this point
        of time
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "32"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 592.5,
          "y": 2440
        }
      }
    note: false
  "32":
    id: "32"
    taskid: 27fd9dc6-2da3-4ce6-8d3f-0c9f371ec239
    type: regular
    task:
      id: 27fd9dc6-2da3-4ce6-8d3f-0c9f371ec239
      version: -1
      name: Close Investigation
      script: CloseInvestigation
      type: regular
      iscommand: false
      brand: ""
    scriptarguments:
      notes: {}
      reason: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 592.5,
          "y": 2615
        }
      }
    note: false
  "33":
    id: "33"
    taskid: 1797f786-c82c-43c0-8ed3-936054b8bd5a
    type: regular
    task:
      id: 1797f786-c82c-43c0-8ed3-936054b8bd5a
      version: -1
      name: Close Investigation
      script: CloseInvestigation
      type: regular
      iscommand: false
      brand: ""
    scriptarguments:
      notes: {}
      reason: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 807.5,
          "y": 1945
        }
      }
    note: false
  "34":
    id: "34"
    taskid: 0d74903f-359a-40ab-8649-1c2ecfd53e6a
    type: regular
    task:
      id: 0d74903f-359a-40ab-8649-1c2ecfd53e6a
      version: -1
      name: Close Investigation
      script: CloseInvestigation
      type: regular
      iscommand: false
      brand: ""
    scriptarguments:
      notes: {}
      reason: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1116,
          "y": 337
        }
      }
    note: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 2660,
        "width": 1446,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
