id: 629426e0-f307-4535-8d41-88c53bdc1789
version: 6
name: only send email
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 58e37787-4981-4334-8398-6694519e5805
    type: start
    task:
      id: 58e37787-4981-4334-8398-6694519e5805
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 42
        }
      }
    note: false
  "1":
    id: "1"
    taskid: e88c21a7-51b3-49f4-86ff-c91f155094a9
    type: regular
    task:
      id: e88c21a7-51b3-49f4-86ff-c91f155094a9
      version: -1
      name: SendEmail
      description: |-
        Send an email with the specified parameters.
        Attachments are provided as a comma-separated list of entry IDs.
        Example usage: !SendEmail subject="File from war room" body="Please see the attached file. --DBot" to=jane@acme.com cc=john@acme.com attachIDs=89@3,46@3
      script: exchange_mail_test|||send-mail
      type: regular
      iscommand: true
      brand: exchange_mail_test
    scriptarguments:
      attachIDs: {}
      attachNames: {}
      bcc: {}
      body: {}
      cc: {}
      fileName: {}
      htmlBody: {}
      replyTo: {}
      subject:
        simple: Test Mail from demisto
      to:
        simple: nidhi.trivedi@wipro.com
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 230
        }
      }
    note: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 283,
        "width": 380,
        "x": 450,
        "y": 42
      }
    }
  }
inputs: []
outputs: []
