id: fc8f5d6c-e722-4d3e-80e6-fbc5a6b41438
version: 16
name: TestPlaybookEmail-BS
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 1a8a6ed3-5d6b-431a-8df4-6c562e3baeb9
    type: start
    task:
      id: 1a8a6ed3-5d6b-431a-8df4-6c562e3baeb9
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "7"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": -132
        }
      }
    note: false
  "1":
    id: "1"
    taskid: e153c0db-1e39-4fc3-8309-a138f64a7edf
    type: regular
    task:
      id: e153c0db-1e39-4fc3-8309-a138f64a7edf
      version: -1
      name: ExtractURL
      description: Extract URLs from the given text and place them both as output
        and in the context of a playbook. If given an object, will convert to JSON.
      script: ExtractURL
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      text:
        simple: ${incident.details}
      urlRegex: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 195
        }
      }
    note: false
  "2":
    id: "2"
    taskid: 0cd360d8-65f1-49cf-8a58-a145b7720eaf
    type: regular
    task:
      id: 0cd360d8-65f1-49cf-8a58-a145b7720eaf
      version: -1
      name: URL reputation
      script: VirusTotal|||url
      type: regular
      iscommand: true
      brand: VirusTotal
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      long: {}
      retries:
        simple: "5"
      sampleSize: {}
      submitWait: {}
      threshold: {}
      url:
        simple: ${URL.Data}
      using:
        simple: VirusTotal_instance_1
      wait: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 370
        }
      }
    note: false
  "3":
    id: "3"
    taskid: 9cab2c5e-47c2-4c6f-826f-6cc195a562fa
    type: condition
    task:
      id: 9cab2c5e-47c2-4c6f-826f-6cc195a562fa
      version: -1
      name: Check if there is any malicious url?
      description: Check URL Reputation
      script: IsMaliciousIndicatorFound
      type: condition
      iscommand: false
      brand: VirusTotal
    nexttasks:
      "no":
      - "5"
      "yes":
      - "4"
    scriptarguments:
      includeSuspicious:
        simple: "yes"
      maliciousQueryOverride: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 545
        }
      }
    note: false
  "4":
    id: "4"
    taskid: 104a0b89-654b-4b0a-8aa0-e2c582c6f51b
    type: regular
    task:
      id: 104a0b89-654b-4b0a-8aa0-e2c582c6f51b
      version: -1
      name: Malicious URL found
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "8"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 720
        }
      }
    note: false
  "5":
    id: "5"
    taskid: 7e509fe1-8233-48ea-8f94-4685aa4179ea
    type: regular
    task:
      id: 7e509fe1-8233-48ea-8f94-4685aa4179ea
      version: -1
      name: No Malicious URL found, so closing the ticket
      script: CloseInvestigation
      type: regular
      iscommand: false
      brand: ""
    scriptarguments:
      notes: {}
      reason: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 720
        }
      }
    note: false
  "6":
    id: "6"
    taskid: b33eb07b-12f5-4e91-8544-3f00c9759a52
    type: regular
    task:
      id: b33eb07b-12f5-4e91-8544-3f00c9759a52
      version: -1
      name: Close Investigation
      script: CloseInvestigation
      type: regular
      iscommand: false
      brand: ""
    scriptarguments:
      notes: {}
      reason: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1091
        }
      }
    note: false
  "7":
    id: "7"
    taskid: 31933cbe-4570-45c6-872b-2beacd9926c5
    type: regular
    task:
      id: 31933cbe-4570-45c6-872b-2beacd9926c5
      version: -1
      name: Delete context
      script: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    scriptarguments:
      all:
        simple: "yes"
      key: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 8
        }
      }
    note: false
  "8":
    id: "8"
    taskid: b23a6230-c06f-4c65-8b53-7640c97a2560
    type: regular
    task:
      id: b23a6230-c06f-4c65-8b53-7640c97a2560
      version: -1
      name: Assign to the respective person
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "6"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 900
        }
      }
    note: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1318,
        "width": 810,
        "x": 50,
        "y": -132
      }
    }
  }
inputs: []
outputs: []
