id: 5af19c48-8822-42bf-89a5-d356c3d6eb6a
version: 5
name: ravikishore_send_read_email
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: c10a0b01-3a99-4010-8bd4-8b09907906f5
    type: start
    task:
      id: c10a0b01-3a99-4010-8bd4-8b09907906f5
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
    note: false
  "1":
    id: "1"
    taskid: 57b2d9b5-6675-4f67-8848-cf34e418f4f2
    type: regular
    task:
      id: 57b2d9b5-6675-4f67-8848-cf34e418f4f2
      version: -1
      name: Send an Email to related user
      description: |-
        Send an email with the specified parameters.
        Attachments are provided as a comma-separated list of entry IDs.
        Example usage: !SendEmail subject="File from war room" body="Please see the attached file. --DBot" to=jane@acme.com cc=john@acme.com attachIDs=89@3,46@3
      script: EmailAskUser
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      additionalOptions: {}
      attachIds: {}
      bcc: {}
      bodyType: {}
      cc: {}
      email:
        simple: ravi.vundavalli@wipro.com
      message:
        simple: 'please respond '
      option1:
        simple: "yes"
      option2:
        simple: "no"
      persistent: {}
      replyAddress: {}
      replyEntriesTag: {}
      retries: {}
      roles: {}
      subject:
        simple: 'reply please '
      task: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 230
        }
      }
    note: false
  "2":
    id: "2"
    taskid: 47e0e260-c423-4249-8c57-968c87655d30
    type: regular
    task:
      id: 47e0e260-c423-4249-8c57-968c87655d30
      version: -1
      name: Wating ..
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 430
        }
      }
    note: false
  "3":
    id: "3"
    taskid: f51fd6c2-7f8e-48c3-88ad-9dcc3300b5c9
    type: condition
    task:
      id: f51fd6c2-7f8e-48c3-88ad-9dcc3300b5c9
      version: -1
      name: Process user response from email
      script: EmailAskUserResponse
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "no":
      - "4"
      "yes":
      - "5"
    scriptarguments:
      responseEntryId:
        simple: ${lastCompletedTaskEntries}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 662
        }
      }
    note: false
  "4":
    id: "4"
    taskid: 6da7cc6b-27ca-4694-8a05-10f09e7ebe53
    type: regular
    task:
      id: 6da7cc6b-27ca-4694-8a05-10f09e7ebe53
      version: -1
      name: close
      script: CloseInvestigation
      type: regular
      iscommand: false
      brand: ""
    scriptarguments:
      notes: {}
      reason: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 455,
          "y": 945
        }
      }
    note: false
  "5":
    id: "5"
    taskid: 0755f1ee-ab07-46c4-808d-df4c425850d5
    type: regular
    task:
      id: 0755f1ee-ab07-46c4-808d-df4c425850d5
      version: -1
      name: read context
      script: PrintContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "4"
    scriptarguments:
      outputformat:
        simple: ${EmailAskUserResponse}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 910,
          "y": 935
        }
      }
    note: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 990,
        "width": 840,
        "x": 450,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
