id: 5884f8ef-fd1c-4ee5-84b8-96b833fd2fb4
version: 4
name: Extract_varma
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 75f698b5-a53a-48b0-8c0e-c992cd46aae5
    type: start
    task:
      id: 75f698b5-a53a-48b0-8c0e-c992cd46aae5
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
      - "14"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 50
        }
      }
    note: false
  "1":
    id: "1"
    taskid: 4167dcea-4784-4f87-8401-a27d853116b3
    type: condition
    task:
      id: 4167dcea-4784-4f87-8401-a27d853116b3
      version: -1
      name: Do we have any attachment file?
      script: Exists
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "2"
    scriptarguments:
      value: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 255,
          "y": 195
        }
      }
    note: false
  "2":
    id: "2"
    taskid: 72d42ec3-28cb-459c-8dac-03d4ee96a59c
    type: regular
    task:
      id: 72d42ec3-28cb-459c-8dac-03d4ee96a59c
      version: -1
      name: word doc file
      description: Takes an input docx file (entryID) as an input and saves an output
        text file (file entry) with the original file's contents.
      script: ParseWordDoc
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      entryID:
        simple: ${File(val.Extension=='docx').EntryID}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 370
        }
      }
    note: false
  "3":
    id: "3"
    taskid: 446e7f8c-b75e-462e-87d9-1660cdaad5e0
    type: regular
    task:
      id: 446e7f8c-b75e-462e-87d9-1660cdaad5e0
      version: -1
      name: Read file from the copied text
      description: Load the contents of a file into context.
      script: ReadFile
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "4"
      - "5"
    scriptarguments:
      entryID:
        simple: ${File(val.Extension=='txt').EntryID}
      maxFileSize: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 545
        }
      }
    note: false
  "4":
    id: "4"
    taskid: c59705bc-c4e7-48c4-82b6-577f6e79d1b2
    type: regular
    task:
      id: c59705bc-c4e7-48c4-82b6-577f6e79d1b2
      version: -1
      name: Ip Extract
      description: Extract IPs from the given text and place them both as output and
        in the context of a playbook.
      script: ExtractIP
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "7"
    scriptarguments:
      text:
        simple: ${FileData}${incident.details}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 720
        }
      }
    note: false
  "5":
    id: "5"
    taskid: 2c76896a-c9c8-43d8-87ce-94fa31b03610
    type: regular
    task:
      id: 2c76896a-c9c8-43d8-87ce-94fa31b03610
      version: -1
      name: Extract Domain
      description: Extract Domains from the given text and place them both as output
        and in the context of a playbook. If given an object, will convert to JSON.
      script: ExtractDomain
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "10"
    scriptarguments:
      calcReputation: {}
      extractFromEmails: {}
      markAsIndicator: {}
      text:
        simple: ${FileData}${incident.details}
      tldList: {}
      urlRegex: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 592.5,
          "y": 720
        }
      }
    note: false
  "6":
    id: "6"
    taskid: a92617df-e6a5-4d30-873e-e8a1774f9967
    type: regular
    task:
      id: a92617df-e6a5-4d30-873e-e8a1774f9967
      version: -1
      name: Extract URL
      description: Extract URLs from the given text and place them both as output
        and in the context of a playbook. If given an object, will convert to JSON.
      script: ExtractURL
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "8"
    scriptarguments:
      text:
        simple: ${FileData}${incident.details}
      urlRegex: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1135,
          "y": 720
        }
      }
    note: false
  "7":
    id: "7"
    taskid: bd57b79a-7a45-4a66-830e-6b82364605ec
    type: regular
    task:
      id: bd57b79a-7a45-4a66-830e-6b82364605ec
      version: -1
      name: IPReputation
      description: A context script for IP entities
      script: IPReputation
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "9"
    scriptarguments:
      ip:
        simple: ${IP.Address}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 895
        }
      }
    note: false
  "8":
    id: "8"
    taskid: d4a2a2df-f875-461e-866a-c0ae1117765a
    type: regular
    task:
      id: d4a2a2df-f875-461e-866a-c0ae1117765a
      version: -1
      name: URL Reputation
      description: A context script for URL entities
      script: URLReputation
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "10"
    scriptarguments:
      url:
        simple: ${URL.Data}${FileData}${incident.details}${File.Text}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1135,
          "y": 895
        }
      }
    note: false
  "9":
    id: "9"
    taskid: b7a0bba6-da5f-458c-8552-83c5ebe9de41
    type: condition
    task:
      id: b7a0bba6-da5f-458c-8552-83c5ebe9de41
      version: -1
      name: Check Malicious
      script: IsMaliciousIndicatorFound
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "11"
    scriptarguments:
      includeSuspicious:
        simple: "yes"
      maliciousQueryOverride: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1070
        }
      }
    note: false
  "10":
    id: "10"
    taskid: 8f3d63a6-2ec6-476f-8168-7bb0da968a63
    type: condition
    task:
      id: 8f3d63a6-2ec6-476f-8168-7bb0da968a63
      version: -1
      name: check malicious
      script: IsMaliciousIndicatorFound
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "no":
      - "12"
      - "11"
    scriptarguments:
      includeSuspicious:
        simple: "yes"
      maliciousQueryOverride: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 930,
          "y": 1070
        }
      }
    note: false
  "11":
    id: "11"
    taskid: 3e558b6e-c305-44ab-84f4-1c7b6c140645
    type: regular
    task:
      id: 3e558b6e-c305-44ab-84f4-1c7b6c140645
      version: -1
      name: asign to user
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "13"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 60,
          "y": 1245
        }
      }
    note: false
  "12":
    id: "12"
    taskid: e7e6f4d7-55dd-457c-8a41-be5590f719ef
    type: regular
    task:
      id: e7e6f4d7-55dd-457c-8a41-be5590f719ef
      version: -1
      name: CloseInvestigation
      description: Close an investigation
      script: CloseInvestigation
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "13"
    scriptarguments:
      notes: {}
      reason: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 940,
          "y": 1245
        }
      }
    note: false
  "13":
    id: "13"
    taskid: 39ecd025-e465-4034-8c58-5f6d3a361020
    type: title
    task:
      id: 39ecd025-e465-4034-8c58-5f6d3a361020
      version: -1
      name: closeInvestigation
      description: Close the current investigation
      type: title
      iscommand: false
      brand: Builtin
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 592.5,
          "y": 1420
        }
      }
    note: false
  "14":
    id: "14"
    taskid: 68cb4a99-a84a-4ac6-8c79-1d24d39909f0
    type: condition
    task:
      id: 68cb4a99-a84a-4ac6-8c79-1d24d39909f0
      version: -1
      name: Do we have any attachment?
      description: Load the contents and metadata of a PDF file into context.
      script: Exists
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "no":
      - "16"
      - "2"
      "yes":
      - "15"
    scriptarguments:
      value:
        simple: ${File(val.Extension=='pdf')}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 695,
          "y": 195
        }
      }
    note: false
  "15":
    id: "15"
    taskid: 2a842be1-9860-48ec-85a3-d2dc9152d052
    type: regular
    task:
      id: 2a842be1-9860-48ec-85a3-d2dc9152d052
      version: -1
      name: ReadPDFFile
      description: Load the contents and metadata of a PDF file into context.
      script: ReadPDFFile
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "6"
      - "5"
    scriptarguments:
      entryID:
        simple: ${File(val.Extension=='pdf').EntryID}
      maxFileSize: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1105,
          "y": 445
        }
      }
    note: false
  "16":
    id: "16"
    taskid: 0521e6c5-39ed-4a3f-89ac-bc25df0bb025
    type: regular
    task:
      id: 0521e6c5-39ed-4a3f-89ac-bc25df0bb025
      version: -1
      name: CloseInvestigation
      description: Close an investigation
      script: CloseInvestigation
      type: regular
      iscommand: false
      brand: ""
    scriptarguments:
      notes: {}
      reason: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 684,
          "y": 465
        }
      }
    note: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1435,
        "width": 1465,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
