id: 237139a2-f508-4913-8f78-ee7c0dc4b771
version: 12
name: Test3AttachDoc
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 6cd3e0c7-66e1-4662-8464-09aa4e42b03e
    type: start
    task:
      id: 6cd3e0c7-66e1-4662-8464-09aa4e42b03e
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "11"
      - "12"
      - "13"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 490,
          "y": 50
        }
      }
    note: false
  "2":
    id: "2"
    taskid: 8cd2acd9-b43b-42af-8a73-f42475aa49d4
    type: title
    task:
      id: 8cd2acd9-b43b-42af-8a73-f42475aa49d4
      version: -1
      name: End
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 387.5,
          "y": 1245
        }
      }
    note: false
  "3":
    id: "3"
    taskid: c8b8f1b3-a668-4b9b-8c6d-9ff876285138
    type: regular
    task:
      id: c8b8f1b3-a668-4b9b-8c6d-9ff876285138
      version: -1
      name: Parse
      script: ParseWordDoc
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "4"
    scriptarguments:
      entryID:
        simple: ${File(val.Extension=='docx').EntryID}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 347,
          "y": 344
        }
      }
    note: false
  "4":
    id: "4"
    taskid: 5fd15e01-415c-4887-8b5a-1201a20d759e
    type: regular
    task:
      id: 5fd15e01-415c-4887-8b5a-1201a20d759e
      version: -1
      name: read Text file
      script: ReadFile
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "5"
      - "6"
    scriptarguments:
      entryID:
        simple: ${File(val.Extension=='txt').EntryID}
      maxFileSize: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 357.5,
          "y": 545
        }
      }
    note: false
  "5":
    id: "5"
    taskid: 4b6249d5-08ba-4204-86a7-c43753d1028c
    type: regular
    task:
      id: 4b6249d5-08ba-4204-86a7-c43753d1028c
      version: -1
      name: IP Extraction
      script: ExtractIP
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "7"
    scriptarguments:
      text:
        simple: ${FileData}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 357.5,
          "y": 720
        }
      }
    note: false
  "6":
    id: "6"
    taskid: e93c6ebd-0db8-4b8e-8293-dc553e70e101
    type: regular
    task:
      id: e93c6ebd-0db8-4b8e-8293-dc553e70e101
      version: -1
      name: Url Extraction
      script: ExtractURL
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "9"
    scriptarguments:
      text:
        simple: ${FileData}
      urlRegex: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 807.5,
          "y": 720
        }
      }
    note: false
  "7":
    id: "7"
    taskid: d5f37a6e-dc20-4925-8992-290786433a78
    type: condition
    task:
      id: d5f37a6e-dc20-4925-8992-290786433a78
      version: -1
      name: IP Empty Condition
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "8"
      "yes":
      - "2"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEmpty
          left:
            value:
              simple: IP.Address
            iscontext: true
    view: |-
      {
        "position": {
          "x": 357.5,
          "y": 895
        }
      }
    note: false
  "8":
    id: "8"
    taskid: 864d1a7c-341f-43dc-8583-b2724770d2b3
    type: regular
    task:
      id: 864d1a7c-341f-43dc-8583-b2724770d2b3
      version: -1
      name: IP Reputation
      script: VirusTotal|||ip
      type: regular
      iscommand: true
      brand: VirusTotal
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      ip:
        simple: ${IP.Address}
      long: {}
      retries: {}
      sampleSize: {}
      threshold: {}
      wait: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1070
        }
      }
    note: false
  "9":
    id: "9"
    taskid: 95ae7a81-3410-42ea-8ab9-22e83769eb45
    type: condition
    task:
      id: 95ae7a81-3410-42ea-8ab9-22e83769eb45
      version: -1
      name: URL Empty Condition
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "10"
      "yes":
      - "2"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEmpty
          left:
            value:
              simple: URL.Data
            iscontext: true
    view: |-
      {
        "position": {
          "x": 807.5,
          "y": 895
        }
      }
    note: false
  "10":
    id: "10"
    taskid: 9122bf28-af60-42f4-8cf3-b5b26f6bebd8
    type: regular
    task:
      id: 9122bf28-af60-42f4-8cf3-b5b26f6bebd8
      version: -1
      name: URL repuTation
      script: VirusTotal|||url
      type: regular
      iscommand: true
      brand: VirusTotal
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      long: {}
      retries: {}
      sampleSize: {}
      submitWait: {}
      threshold: {}
      url:
        simple: ${URL.Data}
      wait: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 807.5,
          "y": 1070
        }
      }
    note: false
  "11":
    id: "11"
    taskid: 66ca5d4b-d9c9-4e27-8aa1-ab735e45739c
    type: condition
    task:
      id: 66ca5d4b-d9c9-4e27-8aa1-ab735e45739c
      version: -1
      name: WordDocCheck
      script: Exists
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "no":
      - "2"
      "yes":
      - "3"
    scriptarguments:
      value:
        simple: ${File(val.Extension=='docx').EntryID}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 132.5,
          "y": 195
        }
      }
    note: false
  "12":
    id: "12"
    taskid: b640554f-1074-43d8-84d4-ccab13d122a7
    type: condition
    task:
      id: b640554f-1074-43d8-84d4-ccab13d122a7
      version: -1
      name: TextAttachmentCheck
      script: Exists
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "no":
      - "2"
      "yes":
      - "4"
    scriptarguments:
      value:
        simple: ${File(val.Extension=='txt').EntryID}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 678,
          "y": 210
        }
      }
    note: false
  "13":
    id: "13"
    taskid: 2c7a4cfe-8b1d-44c0-8555-a00f95779c7a
    type: condition
    task:
      id: 2c7a4cfe-8b1d-44c0-8555-a00f95779c7a
      version: -1
      name: PDFAttachCheck
      script: Exists
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "no":
      - "2"
      "yes":
      - "14"
    scriptarguments:
      value:
        simple: ${File(val.Extension=='pdf').EntryID}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1128,
          "y": 231
        }
      }
    note: false
  "14":
    id: "14"
    taskid: ef4770fc-1f11-4b1f-82d7-1119a0e7730a
    type: regular
    task:
      id: ef4770fc-1f11-4b1f-82d7-1119a0e7730a
      version: -1
      name: PDFExtract
      script: ReadPDFFile
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "15"
      - "9"
    scriptarguments:
      entryID:
        simple: ${File(val.Extension=='pdf').EntryID}
      maxFileSize: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1024,
          "y": 450
        }
      }
    note: false
  "15":
    id: "15"
    taskid: 5bdb6540-9a36-487d-8e4b-005758cab032
    type: regular
    task:
      id: 5bdb6540-9a36-487d-8e4b-005758cab032
      version: -1
      name: IP Extraction
      script: ExtractIP
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "7"
    scriptarguments:
      text:
        simple: ${File.Text}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1261,
          "y": 690
        }
      }
    note: false
view: |-
  {
    "linkLabelsPosition": {
      "9_2_yes": 0.44
    },
    "paper": {
      "dimensions": {
        "height": 1260,
        "width": 1591,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
