id: 36aadae9-38c1-4ef9-8391-41519cb71845
version: 31
name: Parsing contents of docx and pdf files- Priyanshu
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: cb5dc3dd-d607-43cc-84cf-c21b01f3411a
    type: start
    task:
      id: cb5dc3dd-d607-43cc-84cf-c21b01f3411a
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "12"
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 500,
          "y": 50
        }
      }
    note: false
  "1":
    id: "1"
    taskid: 438abe3b-4bfc-4875-8c30-00f82155fb85
    type: condition
    task:
      id: 438abe3b-4bfc-4875-8c30-00f82155fb85
      version: -1
      name: Is there a PDF file ?
      script: Exists
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "14"
      "yes":
      - "2"
    scriptarguments:
      value:
        simple: ${File(val.Extension=='pdf')}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 715,
          "y": 195
        }
      }
    note: false
  "2":
    id: "2"
    taskid: f4fbcf5f-2234-4fee-84bb-32bd73d97812
    type: regular
    task:
      id: f4fbcf5f-2234-4fee-84bb-32bd73d97812
      version: -1
      name: Read PDF
      script: ReadPDFFile
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "4"
    scriptarguments:
      entryID:
        simple: ${File(val.Extension=='pdf').EntryID}
      maxFileSize: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 490,
          "y": 370
        }
      }
    note: false
  "3":
    id: "3"
    taskid: e622a43b-8543-4a3f-8026-34ef7b6568d2
    type: regular
    task:
      id: e622a43b-8543-4a3f-8026-34ef7b6568d2
      version: -1
      name: Read Docx
      script: ParseWordDoc
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "13"
    scriptarguments:
      entryID:
        simple: ${File(val.Extension=='docx').EntryID}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 60,
          "y": 370
        }
      }
    note: false
  "4":
    id: "4"
    taskid: d8c115e0-2f40-48a6-89de-0ac15a882bb5
    type: regular
    task:
      id: d8c115e0-2f40-48a6-89de-0ac15a882bb5
      version: -1
      name: Extract URL from pdf
      script: ExtractURL
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "7"
    scriptarguments:
      text:
        simple: ${URL.Data}
      urlRegex: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 490,
          "y": 545
        }
      }
    note: false
  "5":
    id: "5"
    taskid: 874bc916-c943-441e-87a2-11734a217d83
    type: regular
    task:
      id: 874bc916-c943-441e-87a2-11734a217d83
      version: -1
      name: Extract URL from doc
      script: ExtractURL
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "6"
    scriptarguments:
      text:
        simple: ${FileData}
      urlRegex: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 60,
          "y": 720
        }
      }
    note: false
  "6":
    id: "6"
    taskid: f5be0aa5-4925-47cc-81b5-cef7d55f678d
    type: regular
    task:
      id: f5be0aa5-4925-47cc-81b5-cef7d55f678d
      version: -1
      name: Check URL reputation
      script: VirusTotal|||url
      type: regular
      iscommand: true
      brand: VirusTotal
    nexttasks:
      '#none#':
      - "8"
    scriptarguments:
      long: {}
      retries: {}
      sampleSize: {}
      submitWait: {}
      threshold: {}
      url:
        simple: ${URL.Data}
      wait: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 60,
          "y": 895
        }
      }
    note: false
  "7":
    id: "7"
    taskid: 5540dfa3-eaa0-4823-8692-ad5485559114
    type: regular
    task:
      id: 5540dfa3-eaa0-4823-8692-ad5485559114
      version: -1
      name: Check URL reputation
      script: VirusTotal|||url
      type: regular
      iscommand: true
      brand: VirusTotal
    nexttasks:
      '#none#':
      - "11"
    scriptarguments:
      long: {}
      retries: {}
      sampleSize: {}
      submitWait: {}
      threshold: {}
      url:
        simple: ${URL.Data}
      wait: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 490,
          "y": 720
        }
      }
    note: false
  "8":
    id: "8"
    taskid: 60c24c47-eec6-4568-8214-77b5c7be9500
    type: condition
    task:
      id: 60c24c47-eec6-4568-8214-77b5c7be9500
      version: -1
      name: Is the URL malicious
      script: IsMaliciousIndicatorFound
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "no":
      - "10"
      "yes":
      - "9"
    scriptarguments:
      extend-context: {}
      includeSuspicious:
        simple: "yes"
      maliciousQueryOverride: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 60,
          "y": 1070
        }
      }
    note: false
  "9":
    id: "9"
    taskid: d7cdf4db-fedb-4fca-88ff-e01c3ede2af8
    type: regular
    task:
      id: d7cdf4db-fedb-4fca-88ff-e01c3ede2af8
      version: -1
      name: Report verdict- Malicious
      type: regular
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 500,
          "y": 1245
        }
      }
    note: false
  "10":
    id: "10"
    taskid: 3db1aaca-0ee8-4d14-85e5-72e315d68534
    type: regular
    task:
      id: 3db1aaca-0ee8-4d14-85e5-72e315d68534
      version: -1
      name: Report Verdict- Non malicious
      type: regular
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1245
        }
      }
    note: false
  "11":
    id: "11"
    taskid: c2ed93a9-9329-4012-8f10-65a031d9ad00
    type: condition
    task:
      id: c2ed93a9-9329-4012-8f10-65a031d9ad00
      version: -1
      name: Is the URL malicious
      script: IsMaliciousIndicatorFound
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "no":
      - "10"
      "yes":
      - "9"
    scriptarguments:
      extend-context: {}
      includeSuspicious:
        simple: "yes"
      maliciousQueryOverride: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 490,
          "y": 1070
        }
      }
    note: false
  "12":
    id: "12"
    taskid: e78c2907-a526-4976-82d2-61f1872f3c6e
    type: condition
    task:
      id: e78c2907-a526-4976-82d2-61f1872f3c6e
      version: -1
      name: Is there a docx  file?
      script: Exists
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "14"
      "yes":
      - "3"
    scriptarguments:
      value:
        simple: ${File(val.Extension=='docx')}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 285,
          "y": 195
        }
      }
    note: false
  "13":
    id: "13"
    taskid: ede9921a-4a8c-444d-8d96-537195c294f4
    type: regular
    task:
      id: ede9921a-4a8c-444d-8d96-537195c294f4
      version: -1
      name: Read the text from file
      script: ReadFile
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "5"
    scriptarguments:
      entryID:
        simple: ${File(val.Extension=='txt').EntryID}
      maxFileSize: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 60,
          "y": 545
        }
      }
    note: false
  "14":
    id: "14"
    taskid: d2f83b9d-8c42-4b65-868b-316e81e4328a
    type: regular
    task:
      id: d2f83b9d-8c42-4b65-868b-316e81e4328a
      version: -1
      name: Close investigation
      script: CloseInvestigation
      type: regular
      iscommand: false
      brand: ""
    scriptarguments:
      notes: {}
      reason: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 930,
          "y": 370
        }
      }
    note: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1290,
        "width": 1260,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
