id: 8c8485f2-00e6-4f83-8558-a34085f33cb6
version: 2
name: ravikishore_read_textfile
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 53b27bf0-7943-4f84-8839-027895a681d3
    type: start
    task:
      id: 53b27bf0-7943-4f84-8839-027895a681d3
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 50
        }
      }
    note: false
  "1":
    id: "1"
    taskid: b16a387a-6930-4272-83b1-7a357af96008
    type: condition
    task:
      id: b16a387a-6930-4272-83b1-7a357af96008
      version: -1
      name: Do we have text file?
      script: Exists
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "no":
      - "3"
      "yes":
      - "2"
    scriptarguments:
      value:
        simple: ${File(val.Extension=='txt')}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 195
        }
      }
    note: false
  "2":
    id: "2"
    taskid: b0a1511d-36eb-4575-8446-02c7b5af1eb3
    type: regular
    task:
      id: b0a1511d-36eb-4575-8446-02c7b5af1eb3
      version: -1
      name: read content of the file
      description: Load the contents of a file into context.
      script: ReadFile
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      entryID:
        simple: ${File(val.Extension=='txt').EntryID}
      maxFileSize: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
    note: false
  "3":
    id: "3"
    taskid: 7a4892f5-b5f3-4133-88ad-fa602bf017c9
    type: regular
    task:
      id: 7a4892f5-b5f3-4133-88ad-fa602bf017c9
      version: -1
      name: close
      script: CloseInvestigation
      type: regular
      iscommand: false
      brand: ""
    scriptarguments:
      notes: {}
      reason: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 545
        }
      }
    note: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 590,
        "width": 492.5,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
