id: 0a4ca930-dcee-4b25-8e48-3efa67ec6f43
version: 6
name: test mail_varma
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 95a9dac1-2666-45b2-89ae-68dd8399a3c7
    type: start
    task:
      id: 95a9dac1-2666-45b2-89ae-68dd8399a3c7
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 695,
          "y": 50
        }
      }
    note: false
  "1":
    id: "1"
    taskid: 0e9d0ede-f73c-41dd-8f06-e8bdae8cf3c6
    type: regular
    task:
      id: 0e9d0ede-f73c-41dd-8f06-e8bdae8cf3c6
      version: -1
      name: ReadPDFFile
      description: Load the contents and metadata of a PDF file into context.
      script: ReadPDFFile
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      entryID:
        simple: ${File(val.Extension=='pdf').EntryID}
      maxFileSize: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 695,
          "y": 195
        }
      }
    note: false
  "2":
    id: "2"
    taskid: 269d6781-4ee5-41fc-8bfc-7259fe78ad35
    type: regular
    task:
      id: 269d6781-4ee5-41fc-8bfc-7259fe78ad35
      version: -1
      name: ExtractEmail
      description: Extract Emails from the given text and place them both as output
        and in the context of a playbook. If given an object, will convert to JSON.
      script: ExtractEmail
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      text:
        simple: ${URL.Data}${File.Text}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 695,
          "y": 370
        }
      }
    note: false
  "3":
    id: "3"
    taskid: 7715caa2-a4f5-4e95-8b7f-c66dbd10c0be
    type: condition
    task:
      id: 7715caa2-a4f5-4e95-8b7f-c66dbd10c0be
      version: -1
      name: Resume received exiting consent
      script: Exists
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "no":
      - "5"
      "yes":
      - "4"
    scriptarguments:
      value:
        simple: ${Account.Email.Address}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 695,
          "y": 545
        }
      }
    note: false
  "4":
    id: "4"
    taskid: 5cd96556-dedc-49aa-82f3-2baab109b301
    type: regular
    task:
      id: 5cd96556-dedc-49aa-82f3-2baab109b301
      version: -1
      name: Process the app in Oracle hr
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "6"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 720
        }
      }
    note: false
  "5":
    id: "5"
    taskid: 27e0bef4-85a5-490a-839c-d70510b269b7
    type: regular
    task:
      id: 27e0bef4-85a5-490a-839c-d70510b269b7
      version: -1
      name: Obtain Consent
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "11"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1139,
          "y": 720
        }
      }
    note: false
  "6":
    id: "6"
    taskid: b34214d7-af94-4352-8622-fe8490f86719
    type: regular
    task:
      id: b34214d7-af94-4352-8622-fe8490f86719
      version: -1
      name: Standard Recruitment Process
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "7"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 895
        }
      }
    note: false
  "7":
    id: "7"
    taskid: 7b1ced88-761c-416b-87fe-59b23d37b789
    type: condition
    task:
      id: 7b1ced88-761c-416b-87fe-59b23d37b789
      version: -1
      name: offer
      script: Exists
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "no":
      - "8"
      "yes":
      - "12"
    scriptarguments:
      value: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1070
        }
      }
    note: false
  "8":
    id: "8"
    taskid: 709e6f26-1a48-4bc0-8a9c-182a579fdd50
    type: condition
    task:
      id: 709e6f26-1a48-4bc0-8a9c-182a579fdd50
      version: -1
      name: Hold Data As Per
      script: Exists
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "11"
    scriptarguments:
      value: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 882,
          "y": 1281
        }
      }
    note: false
  "9":
    id: "9"
    taskid: ee59f254-bc87-4746-881f-9636097134cb
    type: regular
    task:
      id: ee59f254-bc87-4746-881f-9636097134cb
      version: -1
      name: Retain Data As per policy SAR request
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "13"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1420
        }
      }
    note: false
  "10":
    id: "10"
    taskid: 8e7543cb-13d3-480e-8acc-fb62d1adf467
    type: regular
    task:
      id: 8e7543cb-13d3-480e-8acc-fb62d1adf467
      version: -1
      name: Masking of data as per policy
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "13"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 51,
          "y": 1420
        }
      }
    note: false
  "11":
    id: "11"
    taskid: 983a2679-03ee-4d30-8277-87bfa972d94f
    type: regular
    task:
      id: 983a2679-03ee-4d30-8277-87bfa972d94f
      version: -1
      name: Masking of data as per policy
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "13"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1139,
          "y": 1502
        }
      }
    note: false
  "12":
    id: "12"
    taskid: f1362224-75b4-4998-8a0d-7883006f302c
    type: condition
    task:
      id: f1362224-75b4-4998-8a0d-7883006f302c
      version: -1
      name: Offer Accepted
      script: Exists
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "no":
      - "9"
      - "10"
    scriptarguments:
      value: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 1245
        }
      }
    note: false
  "13":
    id: "13"
    taskid: 423574db-7443-4fda-831c-b96e01f53700
    type: regular
    task:
      id: 423574db-7443-4fda-831c-b96e01f53700
      version: -1
      name: Stop
      type: regular
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1661
        }
      }
    note: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1706,
        "width": 1468,
        "x": 51,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
