id: 5b20191f-0550-4a35-8656-25482c10ec5b
version: 3
name: TestAttachDoc2
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 6cd3e0c7-66e1-4662-8464-09aa4e42b03e
    type: start
    task:
      id: 6cd3e0c7-66e1-4662-8464-09aa4e42b03e
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 640,
          "y": 138
        }
      }
    note: false
  "2":
    id: "2"
    taskid: 8cd2acd9-b43b-42af-8a73-f42475aa49d4
    type: title
    task:
      id: 8cd2acd9-b43b-42af-8a73-f42475aa49d4
      version: -1
      name: End
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 635,
          "y": 846
        }
      }
    note: false
  "3":
    id: "3"
    taskid: c8b8f1b3-a668-4b9b-8c6d-9ff876285138
    type: regular
    task:
      id: c8b8f1b3-a668-4b9b-8c6d-9ff876285138
      version: -1
      name: Parse
      script: ParseWordDoc
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "4"
    scriptarguments:
      entryID:
        simple: ${File(val.Extension=='docx').EntryID}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 640,
          "y": 302
        }
      }
    note: false
  "4":
    id: "4"
    taskid: 5fd15e01-415c-4887-8b5a-1201a20d759e
    type: regular
    task:
      id: 5fd15e01-415c-4887-8b5a-1201a20d759e
      version: -1
      name: read Text file
      script: ReadFile
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "5"
    scriptarguments:
      entryID:
        simple: ${File(val.Extension=='txt').EntryID}
      maxFileSize: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 640,
          "y": 487
        }
      }
    note: false
  "5":
    id: "5"
    taskid: 7627157d-e239-4a56-89cb-38ecc95bf90d
    type: playbook
    task:
      id: 7627157d-e239-4a56-89cb-38ecc95bf90d
      version: -1
      name: MyTest1872018
      playbookId: 0b6fbb3b-b8c8-4c2b-8870-78a99420d9e3
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    separatecontext: true
    view: |-
      {
        "position": {
          "x": 640,
          "y": 676
        }
      }
    note: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 773,
        "width": 385,
        "x": 635,
        "y": 138
      }
    }
  }
inputs: []
outputs: []
