id: b27a9357-5da2-4a1d-86d2-9652f959a0b4
version: 9
name: Testbook
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 122a1413-9f15-455d-8588-236b8801103f
    type: start
    task:
      id: 122a1413-9f15-455d-8588-236b8801103f
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "14"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": -88
        }
      }
    note: false
  "2":
    id: "2"
    taskid: a3e78a51-3fc9-4562-8ebd-b5805c78e6a6
    type: playbook
    task:
      id: a3e78a51-3fc9-4562-8ebd-b5805c78e6a6
      version: -1
      name: Process Email
      playbookId: Process Email
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    separatecontext: true
    view: |-
      {
        "position": {
          "x": 450,
          "y": 210
        }
      }
    note: false
  "3":
    id: "3"
    taskid: c6d43546-d2e6-4aa3-8957-1d9009998bbf
    type: regular
    task:
      id: c6d43546-d2e6-4aa3-8957-1d9009998bbf
      version: -1
      name: Extract Ip
      script: ExtractIP
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "4"
    scriptarguments:
      text:
        simple: ${Email}${details}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 389
        }
      }
    note: false
  "4":
    id: "4"
    taskid: 90870d00-e60e-4894-85cf-3130ee224f36
    type: regular
    task:
      id: 90870d00-e60e-4894-85cf-3130ee224f36
      version: -1
      name: Extract URL
      script: ExtractURL
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "5"
    scriptarguments:
      text:
        simple: ${Email}${details}
      urlRegex: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 568
        }
      }
    note: false
  "5":
    id: "5"
    taskid: 442f9193-6321-47bf-815f-a6bf0ed6c975
    type: regular
    task:
      id: 442f9193-6321-47bf-815f-a6bf0ed6c975
      version: -1
      name: Extract Email Address
      script: ExtractEmail
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "6"
    scriptarguments:
      text:
        simple: ${incident.details}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 750
        }
      }
    note: false
  "6":
    id: "6"
    taskid: 8cf537b8-a2ee-4a5e-8889-c82ce67aaec0
    type: regular
    task:
      id: 8cf537b8-a2ee-4a5e-8889-c82ce67aaec0
      version: -1
      name: Extracrt Domain
      script: ExtractDomain
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "7"
    scriptarguments:
      calcReputation: {}
      extractFromEmails: {}
      markAsIndicator: {}
      text:
        simple: ${incident.details}
      tldList: {}
      urlRegex: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 929
        }
      }
    note: false
  "7":
    id: "7"
    taskid: 0b4dd5ea-67e9-4b92-8b54-27630d050e3e
    type: regular
    task:
      id: 0b4dd5ea-67e9-4b92-8b54-27630d050e3e
      version: -1
      name: Check IP Reputation
      script: IPReputation
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "8"
    scriptarguments:
      ip:
        simple: ${IP.Address}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 1110
        }
      }
    note: false
  "8":
    id: "8"
    taskid: 8a155b25-f03a-43d8-8e52-5614758fac1d
    type: regular
    task:
      id: 8a155b25-f03a-43d8-8e52-5614758fac1d
      version: -1
      name: Check URL Reputation
      script: URLReputation
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "9"
    scriptarguments:
      url:
        simple: ${URL.[0].Data}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 1290
        }
      }
    note: false
  "9":
    id: "9"
    taskid: 8b5be552-1e60-4086-8886-c380554072ad
    type: condition
    task:
      id: 8b5be552-1e60-4086-8886-c380554072ad
      version: -1
      name: Check Malicious
      script: IsMaliciousIndicatorFound
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "no":
      - "12"
      "yes":
      - "11"
    scriptarguments:
      includeSuspicious:
        simple: "yes"
      maliciousQueryOverride: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 1470
        }
      }
    note: false
  "10":
    id: "10"
    taskid: 67072c9f-753b-427a-8ea1-684f7dad4297
    type: title
    task:
      id: 67072c9f-753b-427a-8ea1-684f7dad4297
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 129,
          "y": 1879
        }
      }
    note: false
  "11":
    id: "11"
    taskid: 3f3bba96-c41f-47ab-8d3f-dbec8bb1615a
    type: regular
    task:
      id: 3f3bba96-c41f-47ab-8d3f-dbec8bb1615a
      version: -1
      name: need manual intervention
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "13"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 705,
          "y": 1713
        }
      }
    note: false
  "12":
    id: "12"
    taskid: c7620a01-32c2-4cc6-8d7b-e4a6d4367d2b
    type: regular
    task:
      id: c7620a01-32c2-4cc6-8d7b-e4a6d4367d2b
      version: -1
      name: close investigation
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "10"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 129,
          "y": 1691
        }
      }
    note: false
  "13":
    id: "13"
    taskid: c16ee20f-671e-4935-88ae-629bc79717c0
    type: title
    task:
      id: c16ee20f-671e-4935-88ae-629bc79717c0
      version: -1
      name: done
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 705,
          "y": 1879
        }
      }
    note: false
  "14":
    id: "14"
    taskid: c99f5b84-6b7c-4b4b-862f-16af453a829f
    type: regular
    task:
      id: c99f5b84-6b7c-4b4b-862f-16af453a829f
      version: -1
      name: delete context
      script: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      all:
        simple: "yes"
      key: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 43
        }
      }
    note: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 2032,
        "width": 956,
        "x": 129,
        "y": -88
      }
    }
  }
inputs: []
outputs: []
