id: d5fe930c-c676-48f0-8e09-7c211c149813
version: 3
name: Extractfile_punniya_copy
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: c33f0130-16ad-4d6f-86ac-53c4c827de3a
    type: start
    task:
      id: c33f0130-16ad-4d6f-86ac-53c4c827de3a
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
      - "15"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 715,
          "y": 50
        }
      }
    note: false
  "1":
    id: "1"
    taskid: e94cf4d4-415c-42ef-8a88-c919faa8d3a7
    type: condition
    task:
      id: e94cf4d4-415c-42ef-8a88-c919faa8d3a7
      version: -1
      name: Do we have any attachment?
      script: Exists
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "no":
      - "13"
      "yes":
      - "2"
    scriptarguments:
      value:
        simple: ${File(val.Extension=='docx')}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 295,
          "y": 195
        }
      }
    note: false
  "2":
    id: "2"
    taskid: f5a847dc-0b7c-44c5-8da4-890d39c487a2
    type: regular
    task:
      id: f5a847dc-0b7c-44c5-8da4-890d39c487a2
      version: -1
      name: Read attachment
      script: ParseWordDoc
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      entryID:
        simple: ${File(val.Extension=='docx').EntryID}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 285,
          "y": 370
        }
      }
    note: false
  "3":
    id: "3"
    taskid: 801c1c00-575b-49dc-816f-95b113f8b064
    type: regular
    task:
      id: 801c1c00-575b-49dc-816f-95b113f8b064
      version: -1
      name: Read file from the copied text
      script: ReadFile
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "4"
      - "5"
      - "6"
    scriptarguments:
      entryID:
        simple: ${File(val.Extension=='txt').EntryID}
      maxFileSize: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 285,
          "y": 545
        }
      }
    note: false
  "4":
    id: "4"
    taskid: f9aa1020-52fd-41ef-8850-924cb4b4fd2e
    type: regular
    task:
      id: f9aa1020-52fd-41ef-8850-924cb4b4fd2e
      version: -1
      name: Extract ip
      script: ExtractIP
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "7"
    scriptarguments:
      text:
        simple: ${FileData}${incident.details}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 60,
          "y": 720
        }
      }
    note: false
  "5":
    id: "5"
    taskid: a811674a-7f37-4fd9-8d87-0ec5de01350e
    type: regular
    task:
      id: a811674a-7f37-4fd9-8d87-0ec5de01350e
      version: -1
      name: Extract Domain
      script: ExtractDomain
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "10"
    scriptarguments:
      calcReputation: {}
      extractFromEmails: {}
      markAsIndicator: {}
      text:
        simple: ${FileData}${incident.details}
      tldList: {}
      urlRegex: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 715,
          "y": 720
        }
      }
    note: false
  "6":
    id: "6"
    taskid: 5801e9f2-1509-484a-85eb-aff721069170
    type: regular
    task:
      id: 5801e9f2-1509-484a-85eb-aff721069170
      version: -1
      name: extract url
      script: ExtractURL
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "8"
    scriptarguments:
      text:
        simple: ${FileData}${incident.details}
      urlRegex: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1370,
          "y": 720
        }
      }
    note: false
  "7":
    id: "7"
    taskid: d6a69ba4-8c4e-4345-8922-74f67115afdb
    type: regular
    task:
      id: d6a69ba4-8c4e-4345-8922-74f67115afdb
      version: -1
      name: check IP reputation
      script: IPReputation
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "9"
    scriptarguments:
      ip:
        simple: ${IP.Address}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 60,
          "y": 895
        }
      }
    note: false
  "8":
    id: "8"
    taskid: a274c1c7-69c5-44a2-823d-624a5b72e139
    type: regular
    task:
      id: a274c1c7-69c5-44a2-823d-624a5b72e139
      version: -1
      name: url reputation
      script: URLReputation
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "10"
    scriptarguments:
      url:
        simple: ${URL.Data}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1370,
          "y": 895
        }
      }
    note: false
  "9":
    id: "9"
    taskid: 59d23849-d620-4191-8482-d017693031ad
    type: condition
    task:
      id: 59d23849-d620-4191-8482-d017693031ad
      version: -1
      name: check malicious
      script: IsMaliciousIndicatorFound
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "no":
      - "12"
      "yes":
      - "11"
    scriptarguments:
      extend-context:
        simple: data
      includeSuspicious:
        simple: "yes"
      maliciousQueryOverride: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 60,
          "y": 1070
        }
      }
    note: false
  "10":
    id: "10"
    taskid: fd39e3c1-7f8e-41d1-8208-baac2c03f1ed
    type: condition
    task:
      id: fd39e3c1-7f8e-41d1-8208-baac2c03f1ed
      version: -1
      name: check malicious
      script: IsMaliciousIndicatorFound
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "no":
      - "12"
      "yes":
      - "11"
    scriptarguments:
      extend-context:
        simple: URL Data
      includeSuspicious:
        simple: "yes"
      maliciousQueryOverride: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1155,
          "y": 1070
        }
      }
    note: false
  "11":
    id: "11"
    taskid: b264fcf3-6cce-4b4f-8911-68137eab04e9
    type: regular
    task:
      id: b264fcf3-6cce-4b4f-8911-68137eab04e9
      version: -1
      name: assign it to user
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "14"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1245
        }
      }
    note: false
  "12":
    id: "12"
    taskid: 5001fc92-742b-451e-836b-f67546a8ead0
    type: regular
    task:
      id: 5001fc92-742b-451e-836b-f67546a8ead0
      version: -1
      name: close investigation
      script: CloseInvestigation
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "14"
    scriptarguments:
      notes:
        simple: Task has been successfully completed
      reason: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1165,
          "y": 1245
        }
      }
    note: false
  "13":
    id: "13"
    taskid: c4c87cc1-dafd-4dd1-86c2-50974c2358fb
    type: regular
    task:
      id: c4c87cc1-dafd-4dd1-86c2-50974c2358fb
      version: -1
      name: close investigation
      script: CloseInvestigation
      type: regular
      iscommand: false
      brand: ""
    scriptarguments:
      notes:
        simple: There is no attachements
      reason: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 715,
          "y": 370
        }
      }
    note: false
  "14":
    id: "14"
    taskid: 19124e25-552f-4443-80c6-9b693d1eff20
    type: title
    task:
      id: 19124e25-552f-4443-80c6-9b693d1eff20
      version: -1
      name: close investigation
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 715,
          "y": 1420
        }
      }
    note: false
  "15":
    id: "15"
    taskid: 9530e287-3c9e-4ee5-83c8-f30a67033a46
    type: condition
    task:
      id: 9530e287-3c9e-4ee5-83c8-f30a67033a46
      version: -1
      name: Do we have any attachment?
      script: Exists
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "no":
      - "13"
      "yes":
      - "16"
    scriptarguments:
      value:
        simple: ${File(val.Extension=='txt')}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1135,
          "y": 195
        }
      }
    note: false
  "16":
    id: "16"
    taskid: a6877840-0ee0-411e-84db-806fe210ae28
    type: regular
    task:
      id: a6877840-0ee0-411e-84db-806fe210ae28
      version: -1
      name: Read attachment
      script: ParseWordDoc
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "17"
    scriptarguments:
      entryID:
        simple: ${File(val.Extension=='txt').EntryID}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1145,
          "y": 370
        }
      }
    note: false
  "17":
    id: "17"
    taskid: 3275b4c8-500b-4e1e-87a1-14e4dc6e86d5
    type: regular
    task:
      id: 3275b4c8-500b-4e1e-87a1-14e4dc6e86d5
      version: -1
      name: Read file from the copied text
      script: ReadFile
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "4"
      - "6"
      - "5"
    scriptarguments:
      entryID:
        simple: ${File(val.Extension=='txt').EntryID}
      maxFileSize: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1145,
          "y": 545
        }
      }
    note: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1435,
        "width": 1700,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
