id: c9d84d1a-8392-41de-85bf-28546b56f170
version: 20
name: Content Parsing---Kriti
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 2804d813-411f-412b-8899-1ca13f26345e
    type: start
    task:
      id: 2804d813-411f-412b-8899-1ca13f26345e
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
      - "2"
      - "15"
      - "17"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
    note: false
  "1":
    id: "1"
    taskid: 52ac82d1-af40-4245-8847-f065faad148e
    type: condition
    task:
      id: 52ac82d1-af40-4245-8847-f065faad148e
      version: -1
      name: 'Check if there is a doc file '
      tags:
      - ${File(val.Extension=='docx')}
      script: Exists
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "14"
      "yes":
      - "3"
    scriptarguments:
      value:
        simple: ${File(val.Extension=='docx')}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 90,
          "y": 196
        }
      }
    note: false
  "2":
    id: "2"
    taskid: ac78eef4-c688-4223-8a85-76be470d80df
    type: condition
    task:
      id: ac78eef4-c688-4223-8a85-76be470d80df
      version: -1
      name: 'Check if there is pdf file '
      tags:
      - ${File(val.Extension=='pdf')}
      script: Exists
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "14"
      "yes":
      - "4"
    scriptarguments:
      value:
        simple: ${File(val.Extension=='pdf')}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 653,
          "y": 230
        }
      }
    note: false
  "3":
    id: "3"
    taskid: eb479574-3a51-4ae4-888a-17125a16175b
    type: regular
    task:
      id: eb479574-3a51-4ae4-888a-17125a16175b
      version: -1
      name: Read the doc file
      script: ParseWordDoc
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "5"
    scriptarguments:
      entryID:
        simple: ${File(val.Extension=='docx').EntryID}
      extend-context: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 174,
          "y": 483
        }
      }
    note: false
  "4":
    id: "4"
    taskid: 9b5184a6-bd20-45df-899b-7aba9c28f1b8
    type: regular
    task:
      id: 9b5184a6-bd20-45df-899b-7aba9c28f1b8
      version: -1
      name: Read the pdf file
      script: ReadPDFFile
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "7"
    scriptarguments:
      entryID:
        simple: ${File(val.Extension=='pdf').EntryID}
      maxFileSize: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 653,
          "y": 483
        }
      }
    note: false
  "5":
    id: "5"
    taskid: 6cc29245-fea7-4c4b-8288-26c071700913
    type: regular
    task:
      id: 6cc29245-fea7-4c4b-8288-26c071700913
      version: -1
      name: ' Read the text from file'
      script: ReadFile
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "6"
    scriptarguments:
      entryID:
        simple: ${File(val.Extension=='txt').EntryID}
      maxFileSize: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 174,
          "y": 699
        }
      }
    note: false
  "6":
    id: "6"
    taskid: e46ab82d-57f3-4cf4-8da0-e137941b4a52
    type: regular
    task:
      id: e46ab82d-57f3-4cf4-8da0-e137941b4a52
      version: -1
      name: Extract URL from Doc
      script: ExtractURL
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "8"
    scriptarguments:
      text:
        simple: ${FileData}
      urlRegex: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": -117,
          "y": 869
        }
      }
    note: false
  "7":
    id: "7"
    taskid: 9ee6a39c-317a-42c7-85e8-c189916d434c
    type: regular
    task:
      id: 9ee6a39c-317a-42c7-85e8-c189916d434c
      version: -1
      name: Extract URL from Pdf file
      script: ExtractURL
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "9"
    scriptarguments:
      text:
        simple: ${URL.Data}
      urlRegex: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 654,
          "y": 678
        }
      }
    note: false
  "8":
    id: "8"
    taskid: 5dd4a714-2a42-4667-8865-84e843e5ae87
    type: regular
    task:
      id: 5dd4a714-2a42-4667-8865-84e843e5ae87
      version: -1
      name: Check URL Reputation
      script: VirusTotal|||url
      type: regular
      iscommand: true
      brand: VirusTotal
    nexttasks:
      '#none#':
      - "10"
    scriptarguments:
      long: {}
      retries: {}
      sampleSize: {}
      submitWait: {}
      threshold: {}
      url:
        simple: ${URL.Data}
      wait: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 170,
          "y": 1117
        }
      }
    note: false
  "9":
    id: "9"
    taskid: 06bcb362-de62-456f-8938-e5347148bd23
    type: regular
    task:
      id: 06bcb362-de62-456f-8938-e5347148bd23
      version: -1
      name: Check URL Reputation
      script: VirusTotal|||url
      type: regular
      iscommand: true
      brand: VirusTotal
    nexttasks:
      '#none#':
      - "11"
    scriptarguments:
      long: {}
      retries: {}
      sampleSize: {}
      submitWait: {}
      threshold: {}
      url:
        simple: ${URL.Data}
      wait: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 650,
          "y": 869
        }
      }
    note: false
  "10":
    id: "10"
    taskid: e206478b-e8ee-4258-8ee4-6c82304e39dc
    type: condition
    task:
      id: e206478b-e8ee-4258-8ee4-6c82304e39dc
      version: -1
      name: Check if URL is malicious or not
      script: IsMaliciousIndicatorFound
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "13"
      "yes":
      - "12"
    scriptarguments:
      includeSuspicious:
        simple: "yes"
      maliciousQueryOverride: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 166,
          "y": 1325
        }
      }
    note: false
  "11":
    id: "11"
    taskid: 59bb02d8-dd44-4b99-8050-ea1b02271024
    type: condition
    task:
      id: 59bb02d8-dd44-4b99-8050-ea1b02271024
      version: -1
      name: 'Check if the URL is malicious '
      script: IsMaliciousIndicatorFound
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "13"
      "yes":
      - "12"
    scriptarguments:
      includeSuspicious:
        simple: "yes"
      maliciousQueryOverride: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 650,
          "y": 1068
        }
      }
    note: false
  "12":
    id: "12"
    taskid: 57a495f4-8486-404c-8acc-cddf0ff16da2
    type: regular
    task:
      id: 57a495f4-8486-404c-8acc-cddf0ff16da2
      version: -1
      name: Assign to respective person
      type: regular
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": -96,
          "y": 1571
        }
      }
    note: false
  "13":
    id: "13"
    taskid: dfc17a48-a35c-4d15-822b-e3f71b3dfb4f
    type: regular
    task:
      id: dfc17a48-a35c-4d15-822b-e3f71b3dfb4f
      version: -1
      name: Close Investigation
      script: CloseInvestigation
      type: regular
      iscommand: false
      brand: ""
    scriptarguments:
      notes: {}
      reason: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 408,
          "y": 1582
        }
      }
    note: false
  "14":
    id: "14"
    taskid: 33d99991-5d88-4b2e-8eac-1683d81dd541
    type: regular
    task:
      id: 33d99991-5d88-4b2e-8eac-1683d81dd541
      version: -1
      name: Close Investigation
      script: CloseInvestigation
      type: regular
      iscommand: false
      brand: ""
    scriptarguments:
      notes: {}
      reason: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 968,
          "y": 373
        }
      }
    note: false
  "15":
    id: "15"
    taskid: 957e2c77-a5a7-44b5-8ef1-20b8f2c691cf
    type: condition
    task:
      id: 957e2c77-a5a7-44b5-8ef1-20b8f2c691cf
      version: -1
      name: Check if there is csv file
      script: Exists
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "16"
    scriptarguments:
      value:
        simple: ${File(val.Extension=='csv')}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1416,
          "y": 230
        }
      }
    note: false
  "16":
    id: "16"
    taskid: ecb24a3f-fe21-49d8-8b65-73f37615a899
    type: regular
    task:
      id: ecb24a3f-fe21-49d8-8b65-73f37615a899
      version: -1
      name: Read the csv file
      script: ReadFile
      type: regular
      iscommand: false
      brand: ""
    scriptarguments:
      entryID:
        simple: ${File(val.Extension=='csv').EntryID}
      maxFileSize: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1416,
          "y": 483
        }
      }
    note: false
  "17":
    id: "17"
    taskid: 6cdc9551-f62c-4097-8729-e61d3002145f
    type: condition
    task:
      id: 6cdc9551-f62c-4097-8729-e61d3002145f
      version: -1
      name: Check if there is HTML File
      script: Exists
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "18"
    scriptarguments:
      value:
        simple: ${File(val.Extension=='html')}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1802,
          "y": 121
        }
      }
    note: false
  "18":
    id: "18"
    taskid: ac7798a2-d713-4907-8917-d55d117d7845
    type: regular
    task:
      id: ac7798a2-d713-4907-8917-d55d117d7845
      version: -1
      name: Read HTML File
      script: ReadFile
      type: regular
      iscommand: false
      brand: ""
    scriptarguments:
      entryID:
        simple: ${File(val.Extension=='html').EntryID}
      maxFileSize: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1799,
          "y": 383
        }
      }
    note: false
view: |-
  {
    "linkLabelsPosition": {
      "2_4_yes": 0.25
    },
    "paper": {
      "dimensions": {
        "height": 1627,
        "width": 2299,
        "x": -117,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
